language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t swaroopsalvi/react-test -f ./client/Dockerfile.dev ./client
  
script:
 - docker run -e CI=true swaroopsalvi/react-test npm test
 
after_success:
 - docker build -t swaroopsalvi/multi-client ./client
 - docker build -t swaroopsalvi/multi-nginx ./nginx
 - docker build -t swaroopsalvi/multi-server ./server
 - docker build -t swaroopsalvi/multi-worker ./worker
 
# Login in to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
 - docker push swaroopsalvi/multi-client
 - docker push swaroopsalvi/multi-nginx
 - docker push swaroopsalvi/multi-server
 - docker push swaroopsalvi/multi-worker
 
deploy:
 edge: true
 provider: elasticbeanstalk
 region: us-west-2
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-us-west-2-276587239836
 bucket_path: docker-multi
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY